# Generated by Django 4.0.3 on 2022-05-13 10:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Site', '0051_alter_m_mouse_m_mouse_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='m_mouse',
            name='M_Mouse_Price',
            field=models.DecimalField(blank=True, decimal_places=0, max_digits=19, null=True, verbose_name='Цена компьютерной мышки'),
        ),
    ]
