# Generated by Django 4.0.3 on 2022-05-13 10:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Site', '0052_alter_m_mouse_m_mouse_price'),
    ]

    operations = [
        migrations.AlterField(
            model_name='h_headset',
            name='H_HeadSet_Price',
            field=models.DecimalField(blank=True, decimal_places=0, max_digits=19, null=True, verbose_name='Цена клавиатуры'),
        ),
        migrations.AlterField(
            model_name='k_keyboard',
            name='K_Keyboard_Price',
            field=models.DecimalField(blank=True, decimal_places=0, max_digits=19, null=True, verbose_name='Цена клавиатуры'),
        ),
    ]
